# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: biletFlow
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NzVhOWVlN2Y2MWEyZDNhNDc2YjhkMDljYjcwYTM0N2RmNmE0ZmU3MjMxZTU1Yjg3MGY1NjU2NmM4NGQ5YjljMTBmM2NmZjFmMWNjNjAzOTg0NDVhYmE3NzkzNTY5NzI0Y2M5NTYwNTI5NTdmMzM2ODBjMzE2YWM4OTNmNzNiMDI=
