apply plugin: "war"

bootWar {
    mainClass = "com.biletflow.biletflow.BiletFlowApp"
    includes = ["WEB-INF/**", "META-INF/**"]
}

war {
    enabled = true
    archiveExtension = "war.original"
    includes = ["WEB-INF/**", "META-INF/**"]
}

if (project.hasProperty("e2e")) {
    tasks.named('bootWar') {
        archiveFileName = 'e2e.war'
    }
}
